ci:
  - changed-files:
      - any-glob-to-any-file: [".github/**/*"]

environment:
  - changed-files:
      - any-glob-to-any-file: ["scripts/**/*"]

feature:
  - head-branch: ["^feature"]

enhancement:
  - head-branch: ["^feature"]

refactor:
  - head-branch: ["^refactor"]

fix:
  - head-branch: ["^fix"]

bug:
  - head-branch: ["^fix"]

release:
  - head-branch: ["^release"]

documentation:
  - changed-files:
      - any-glob-to-any-file: ["*.md"]

breaking-change:
  - head-branch: ["^breaking-change"]
