# ビルドステージ
FROM ruby:3.2.3-slim AS builder
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# 必要なパッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends build-essential libpq-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 作業ディレクトリの設定
WORKDIR /app

# bundler のインストール
RUN gem install bundler

# Gemfile のコピーと依存関係のインストール
COPY Gemfile Gemfile.lock ./
RUN bundle install

# 実行ステージ
FROM ruby:3.2.3-slim
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# 必要な実行時パッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends libpq-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 作業ディレクトリの設定
WORKDIR /app

# ビルドステージからの Gem のコピー
COPY --from=builder /usr/local/bundle /usr/local/bundle

# アプリケーションコードのコピー
COPY . .

# 実行コマンド
CMD ["rails", "server", "-b", "0.0.0.0"]
