name: Sync Labels

on:
  push:
    paths:
      - ".github/labels.yml" # labels.ymlファイルが変更された場合にワークフローをトリガー
  workflow_dispatch: # 手動でワークフローを実行できるトリガー

permissions:
  issues: write # Issuesの権限を設定（ラベルの書き込み権限）
  pull-requests: write # Pull Requestの権限を設定（ラベルの書き込み権限）

jobs:
  build:
    runs-on: ubuntu-latest # 最新のUbuntu環境でジョブを実行
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # リポジトリのコードをチェックアウトするアクション
      - name: List files
        run: ls -R # 全てのファイルを再帰的にリスト表示（デバッグ用途）
      - name: Sync Labels
        uses: micnncim/action-label-syncer@v1 # labels.ymlの定義に基づいてGitHubリポジトリのラベルを同期するアクション
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHubトークンを環境変数として設定
        with:
          manifest: .github/labels.yml # ラベルの定義ファイルのパス
